#!/bin/bash
# Custom recovery script generated by diagnostics
# Generated: 2025-08-22 07:29:40

echo "🚀 Starting Custom Source Material Recovery"
echo "CSV File: learningq_research_sample.csv"
echo "YouTube Status: ❌ Rate Limited"
echo "Khan Academy Status: ✅ Working"
echo ""

# Phase 1: Articles only (YouTube rate limited)
echo "📚 Phase 1: Recovering Khan Academy Articles..."
python manage.py recover_source_material learningq_research_sample.csv --skip-youtube --slow-mode

echo "⏳ Waiting 1 hour for YouTube rate limits to reset..."
sleep 3600

# Phase 2: Videos with slow mode
echo "🎥 Phase 2: Recovering YouTube Videos..."
python manage.py recover_source_material learningq_research_sample.csv --slow-mode --force-retry

# Verification
echo "🔍 Verifying results..."
python manage.py verify_source_material learningq_research_sample_recovered.csv --show-details

echo "✅ Recovery script completed!"
