# Generated by Django 4.1.5 on 2024-08-26 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        ("analytics", "0001_initial"),
        ("exams", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="examanalytics",
            name="exam",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="exams.exam"
            ),
        ),
        migrations.AddField(
            model_name="courseanalytics",
            name="course",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="courses.course"
            ),
        ),
    ]
