# Generated by Django 5.1 on 2025-07-28 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0002_initial'),
        ('exams', '0001_initial'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examanalytics',
            name='exam',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='exams.exam'),
        ),
        migrations.AddField(
            model_name='schoolanalytics',
            name='school',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='schools.school'),
        ),
    ]
