# Generated by Django 5.1 on 2025-07-28 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexam',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='result',
            name='student_exam',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='exams.studentexam'),
        ),
        migrations.AddField(
            model_name='answer',
            name='student_exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exams.studentexam'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.CheckConstraint(condition=models.Q(('question_type__in', ['MCQ', 'ESSAY'])), name='valid_question_type'),
        ),
        migrations.AlterUniqueTogether(
            name='studentexam',
            unique_together={('student', 'exam')},
        ),
    ]
