# Generated by Django 5.1 on 2025-08-13 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="e.g., 'Midterm 2023 Sample Questions'", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Brief description of the template')),
                ('question_type', models.CharField(choices=[('MCQ', 'Multiple Choice Question'), ('ESSAY', 'Essay Question'), ('BOTH', 'Both MCQ and Essay')], default='BOTH', max_length=10)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('mixed', 'Mixed Difficulty')], default='mixed', max_length=20)),
                ('template_file', models.FileField(help_text='Upload PDF, TXT, or DOCX file containing sample questions', upload_to='question_templates/')),
                ('template_text', models.TextField(blank=True, help_text='Or paste sample questions directly here')),
                ('is_active', models.BooleanField(default=True, help_text='Use this template for question generation')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_templates', to='courses.course')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
