# Generated by Django 5.1 on 2025-08-13 21:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_questiontemplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursecontent',
            name='course',
        ),
        migrations.RemoveField(
            model_name='coursecontent',
            name='pdf_file',
        ),
        migrations.RemoveField(
            model_name='coursecontent',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='coursecontent',
            name='content_type',
            field=models.CharField(choices=[('pdf', 'PDF Document'), ('text', 'Text Content'), ('transcript', 'Video Transcript')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursecontent',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='course_materials/'),
        ),
        migrations.AddField(
            model_name='coursecontent',
            name='research_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coursecontent',
            name='source_identifier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='coursecontent',
            name='text_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coursecontent',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
