# Generated by Django 5.1 on 2025-08-21 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_add_missing_source_flag'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='expertquestion',
            index=models.Index(fields=['is_missing_source'], name='courses_exp_is_miss_438274_idx'),
        ),
    ]
