# Generated by Django 5.1 on 2025-08-26 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_expertquestion_courses_exp_is_miss_438274_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='expertquestion',
            name='courses_exp_is_miss_438274_idx',
        ),
        migrations.AddField(
            model_name='expertquestion',
            name='is_selected_for_research',
            field=models.BooleanField(default=False, help_text='Indicates if this question is selected for research comparison'),
        ),
        migrations.AddField(
            model_name='expertquestion',
            name='selection_batch',
            field=models.CharField(blank=True, help_text='Batch identifier for selection (e.g., research_baseline_v1)', max_length=100),
        ),
        migrations.AddField(
            model_name='expertquestion',
            name='selection_date',
            field=models.DateTimeField(blank=True, help_text='When this question was selected for research', null=True),
        ),
        migrations.AddField(
            model_name='expertquestion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='expertquestion',
            index=models.Index(fields=['is_selected_for_research'], name='courses_exp_is_sele_910700_idx'),
        ),
        migrations.AddIndex(
            model_name='expertquestion',
            index=models.Index(fields=['selection_batch'], name='courses_exp_selecti_6c09ce_idx'),
        ),
    ]
