# Generated by Django 5.1 on 2025-08-27 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_remove_expertquestion_courses_exp_is_miss_438274_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIGeneratedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('generation_model', models.CharField(max_length=100)),
                ('generation_parameters', models.JSONField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('is_selected_for_evaluation', models.BooleanField(default=True)),
                ('corresponding_expert_question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courses.expertquestion')),
            ],
        ),
    ]
